# Generated by Django 5.2 on 2025-04-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('location', models.CharField(default='Data Center A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_in', models.FloatField()),
                ('network_out', models.FloatField()),
                ('alert_level', models.CharField(blank=True, choices=[('critical', 'Critical'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.server')),
            ],
        ),
    ]
